import { Work_Sans } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import "swiper/css";
import "swiper/css/pagination";

const work_sans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "DXB Care",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${work_sans.className} bg-[#1C1C1C] text-[#E6E6E6]`}>
        {children}
      </body>
    </html>
  );
}
